[default]
extend-ignore-re = [
  "sha256[[:space:]]*=[[:space:]]*\"[[:alnum:]]+\"",
  "hash[[:space:]]*=[[:space:]]*\"[[:alnum:]]+\"",
  # "SHA256:[[:space:]]*[[a-zA-Z0-9+]]+[[:space:]]*",
]

[default.extend-identifiers]
UE4 = "UE4"
UniversalUE4Unlocker = "UniversalUE4Unlocker"

[default.extend-words]
tio = "tio"
