= Home Manager Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Home-Manager: https://nix-community.github.io/home-manager/[Home Manager]

image:https://github.com/jwillikers/home-manager-config/actions/workflows/build.yaml/badge.svg[Build, link=https://github.com/jwillikers/home-manager-config/actions/workflows/build.yaml]

This is my {Home-Manager} configuration.

// todo Configure theme for KDE?

== Getting Started

This Home Manager configuration is currently intended for Fedora Atomic Sway.

Sway::
+
.. Install `gcr` package for secret management.
+
[,sh]
----
sudo rpm-ostree install gcr
----

.. Reboot to apply the changes.
+
[,sh]
----
sudo systemctl reboot
----

.. Enable the `gcr-ssh-agent.socket` systemd socket.
+
[,sh]
----
systemctl --user enable --now gcr-ssh-agent.socket
----

. Install https://lix.systems[Lix].
+
[,sh]
----
curl -sSf -L https://install.lix.systems/lix | sh -s -- install
----

. Configure your user as an allowed and trusted user for Nix.
+
./etc/nix/nix.conf
[,ini]
----
allowed-users = jordan
trusted-users = jordan
----

. Restart the Nix daemon.
+
[,sh]
----
sudo systemctl restart nix-daemon.service
----

. Clone the repository.
+
[,sh]
----
git clone git@github.com:jwillikers/home-manager-config.git
----

. Change into the repository's directory.
+
[,sh]
----
cd home-manager-config
----

. Create a symlink to this repository at `~/.config/home-manager` for convenience.
+
[,sh]
----
rm --recursive ~/.config/home-manager
ln --force --relative --symbolic . ~/.config/home-manager
----

. Create the `ccache` directory the Nix.
+
[,sh]
----
sudo mkdir --parents /nix/var/cache/ccache
----

. Build and activate the Home Manager configuration
+
--
[,sh]
----
nix develop --command home-manager --flake .#jordan@$(hostname --short) switch
----

[TIP]
====
If for any reason the build fails or your computer locks up, there's a good chance that it's related to Nix attempting to build too many jobs simultaneously or not having adequate RAM space to hold the build directory for a package.
These issues can be fixed with configuration options for the Nix daemon in `/etc/nix/nix.conf`.
Use the `max-jobs` option to limit the number of simultaneous jobs.
To build only a single job at a time, this would look like `max-jobs = 1` in the config file.

To prevent running out space in RAM, set the `build-dir` option to a path that is located on disk.
The default `tmp` directory is usually stored in a special filesystem backed by RAM.
To set this to `/var/tmp/nix-daemon`, the line in the config will look like `build-dir = /var/tmp/nix-daemon`.
Be sure to create this directory.

[,sh]
----
sudo mkdir --parents /var/tmp/nix-daemon
----

To apply changes in `/etc/nix/nix.conf`, restart the Nix daemon.

[,sh]
----
sudo systemctl restart nix-daemon.service
----
====
--

. Log out and back in for certain environment variable changes to take effect.

== Resources

* https://nix-community.github.io/home-manager/options.xhtml[Home Manager Configuration Options]
* https://github.com/Misterio77/nix-starter-configs[Misterio77 Nix Starter Config]
* https://github.com/wimpysworld/nix-config[Wimpy's NixOS, nix-darwin & Home Manager Configurations]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[] file.

== License

This repository is licensed under the link:LICENSE[MIT license].

== Copyright

© 2024 Jordan Williams

== Authors

mailto:{email}[{author}]
