= Home Manager Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Forgejo: https://forgejo.org/[Forgejo]
:Home-Manager: https://nix-community.github.io/home-manager/[Home Manager]
:Lix: https://lix.systems/[Lix]
:Nix: https://nixos.org/[Nix]
:sops: https://getsops.io/[sops]
:sops-nix: https://github.com/Mic92/sops-nix[sops-nix]
:Tailscale: https://tailscale.com/[Tailscale]
:Tailscale-on-the-Steam-Deck: https://github.com/tailscale-dev/deck-tailscale[Tailscale on the Steam Deck]
:Nix-Secrets: https://forgejo.jwillikers.io/jwillikers/nix-secrets/[Nix Secrets]
:wayblue: https://github.com/wayblueorg/wayblue[wayblue]

This is my Nix {Home-Manager} configuration.

== Getting Started

This Home Manager configuration is currently intended for {wayblue} Hyprland, Fedora Kinoite, and the Steam Deck running SteamOS.
Secrets are managed with {nix-sops}.
The secrets are stored, encrypted in my {Nix-Secrets} repository hosted on my private {Forgejo} instance.
As such, it's only possible to build this configuration with access to my tailnet, a Forgejo user with permissions to access the repository, a configured SSH key for said user, and the necessary age key to decrypt the secrets.
For completeness and for myself, I'm documenting everything here, including setting all of that up.
For anyone wishing to use this configuration in part or in whole, I'm planning on making a Nix Secrets Example repository which shows how my secrets are organized and how they are named.
This could be used to create your own Nix Secrets repository in place of the mine used in this flake.

. Set up the Steam Deck.
.. On the Steam Deck, switch to _Desktop Mode_.
// todo Automatically set the session type and update the Return to Gaming Mode shortcut via home manager.
.. Open a terminal and configure the Steam Deck to use Plasma Wayland as the default session.
Pass the `plasma-wayland-persistent` argument to the `steamos-session-select` command to boot directly into Plasma Wayland session when booting the Steam Deck.
+
[,sh]
----
steamos-session-select plasma-wayland-persistent
----
+
[NOTE]
====
To revert this behavior, pass the `gamescope` argument to the `steamos-session-select` command.

[,sh]
----
steamos-session-select gamescope
----
====

.. To make the `Return to Gaming Mode` desktop shortcut work when Plasma Wayland is the default session, update the `~/Desktop/Return.desktop` file to be as follows.
The difference here is the `Exec` line.
Unfortunately, this reverts the selected session to boot into SteamOS by default as there is no oneshot session type for SteamOS like there is for Plasma.
It should be possible to get around this with a systemd service unit that sets the session type at boot.
+
.~/Desktop/Return.desktop
[,desktop]
----
[Desktop Entry]
Name=Return to Gaming Mode
# Exec=qdbus6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logout
# Revert to gamescope session.
# Unfortunately, this reverts the selected to boot into SteamOS by default.
Exec=/usr/bin/steamos-session-select gamescope
Icon=steamdeck-gaming-return
Terminal=false
Type=Application
StartupNotify=false
----

.. Open the Konsole terminal.
.. Run the `passwd` command.
.. Follow the prompts to configure a password for your user account.
.. Configure KDE as desired.
I usually have to set up KDE to only use second display when it's docked.
.. Optionally, setup SSH for an easier experience going forward.
... On the Steam Deck, start the SSH server.
+
--
[,sh]
----
sudo systemctl start sshd
----

[CAUTION]
====
This will enable the SSH server on the Steam Deck, which is configured to accept connections using insecure password-based connections.
Only do this on a trusted network.
I would recommend never enabling the SSH server to avoid it being available on an untrusted network.
Stop the SSH server with `sudo systemctl stop sshd`.
====

The rest of these commands can be carried out on another device to configure the Steam Deck from here on.
--

.. On your computer that isn't the Steam Deck, generate an SSH key if you haven't already.
+
[,sh]
----
ssh-keygen
----

.. Follow the prompts, making sure to enter a password for your SSH key.
Do it.

.. Run the command `ssh-copy-id` to copy the SSH public key to the Steam Deck to not have to enter a password every time.
+
--
[,sh]
----
ssh-copy-id deck@steamdeck
----

[NOTE]
====
The Steam Deck advertises itself using the name `steamdeck` over multicast DNS.
This will probably only work on a local network like your home network.
Depending on your network set up mDNS may not be supported.
If this host isn't found, locate the IP address on the Steam Deck by running the `ip addr` command or checking Plasma's networking settings.
====
--

.. Enter the password you created for the Steam Deck user account when prompted.

.. Connect to the Steam Deck over SSH.
+
[,sh]
----
ssh deck@steamdeck
----

. Configure access as necessary for the local Forgejo instance at https://forgejo.jwillikers.io in order to have access to the {Nix-Secrets} repository.
.. Create a dedicated user account for a system which only requires read access to the repository.
For the Steam Deck, I created the `deck` user account for this purpose and shared the {Nix-Secrets} repository with this user, giving it read-only access in the repository's settings.
On my development systems, I don't need to create an account as I'll use the `jordan` account that owns the {Nix-Secrets} repository.
.. Generate an SSH key for this user.
+
[,sh]
----
ssh-keygen
----

.. Use a password for the SSH key, when prompted.
.. Print out the public SSH key.
Assuming the key previously generated was `~/.ssh/id_ed25519`, the command will be as follows.
+
[,sh]
----
cat ~/.ssh/id_ed25519.pub
----

.. Upload that public SSH key to the Forgejo user's SSH keys.

. Add your user to the `input` group to allow Stretchly to properly detect idle time.

.. On Fedora Atomic, the _input_ group does not exist in the `/etc/group`, so it must be added.
+
[,sh]
----
echo $(getent group input) | sudo tee --append /etc/group
----

.. Add your user to the `input` group to allow Stretchly to properly detect idle time.
+
[,sh]
----
sudo usermod --append --group input $USER
----

.. Log out and back in for the group change to take effect.

. Configure Nextcloud access for Ludusavi game save synchronization.
.. Create Nextcloud accounts on https://cloud.jwillikers.io[my Nextcloud instance] for `jordan` and `deck`.
.. Create the directory `ludusavi-backup` under the `jordan` account on Nextcloud and share it with the `deck` user.
.. Generate a Nextcloud app password for each user in the user's security settings in Nextcloud.
.. Add the Nextcloud app passwords to the {Nix-Secrets} repository.
These will be used by Ludusavi and Rclone to sync game saves.
Updating the {Nix-Secrets} repository in the following steps should be done from the development machine, not over SSH on the Steam Deck.
... Follow the directions in the {Nix-Secrets} repository to configure access to the repository over Tailscale and clone the repository locally.
... Change into the {Nix-Secrets} repository's directory.
+
[,sh]
----
cd ~/Projects/nix-secrets
----
... Edit the secrets file for each user with sops.
The command to do this for the `deck` user is shown below.
+
[,sh]
----
nix shell nixpkgs#sops --command sops users/deck.yaml
----
... Finally, add the Nextcloud app password to the YAML secrets file.
The key must be nested under the the host name and named as `nextcloud-ludusavi`.
For the `deck` user, the YAML layout should appear like this.
+
.nix-secrets/users/deck.yaml
[,yaml]
----
steamdeck:
  nextcloud-ludusavi: <Nextcloud App Password>
----
... Save the file and close the editor.
... Repeat as necessary to add the app password for the `jordan` user.
... Commit the changes to the repository.
+
[,sh]
----
git commit --all --message "Add Nextcloud app password for ludusavi"
----
... Push the changes to Forgejo.
+
[,sh]
----
git push
----
... Now update the `home-manager-config` repository to pull in the changes to the {Nix-Secrets} repository.
From the `home-manager-config` repository's directory, run the following command.
+
[,sh]
----
nix flake update nix-secrets
----
... Commit the changes to the repository.
+
[,sh]
----
git commit --all --message "Update nix-secrets""
----
... Push the changes.
+
[,sh]
----
git push
----

. Create a directory in which to keep source code.
I use the `~/Projects` directory for this.
+
[,sh]
----
mkdir --parents ~/Projects
----

. Install and configure {Tailscale}.
+
Fedora Atomic::
+
.. Install Tailscale.
+
[,sh]
----
sudo rpm-ostree install tailscale
----

.. Reboot to apply the change.
+
[,sh]
----
sudo systemctl reboot
----

.. Authenticate Tailscale.
+
[,sh]
----
sudo tailscale up --qr --operator=jordan
----

Steam Deck:: Install Tailscale using the installer script from the {Tailscale-on-the-Steam-Deck} repository.
+
.. Clone the repository.
+
[,sh]
----
git -C ~/Projects clone https://github.com/tailscale-dev/deck-tailscale.git
----

.. Change to the repository's directory.
+
[,sh]
----
cd ~/Projects/deck-tailscale
----

.. Execute the `tailscale.sh` script.
This script installs Tailscale under `/opt/tailscale`.
+
[,sh]
----
sudo bash tailscale.sh
----

.. Authenticate Tailscale.
+
[,sh]
----
sudo /opt/tailscale/tailscale up --qr --operator=deck
----

.. Run the command to update Tailscale.
+
[,sh]
----
sudo /opt/tailscale/tailscale update
----

.. If that works, enable automatic updates.
+
[,sh]
----
sudo /opt/tailscale/tailscale set --auto-update
----

. In order to install Nix on Fedora Atomic distributions, enable a transient root to fix issues with `composefs` not allowing the creation of the `/nix` directory.
This is at least the case with Fedora 42.
We'll see if it gets fixed in later versions.

.. Create the file `/etc/ostree/prepare-root.conf` with the following contents.
+
./etc/ostree/prepare-root.conf
[,ini]
----
[composefs]
enabled = yes
[root]
transient = true
----

.. Apply this file to the initramfs.
+
[,sh]
----
sudo rpm-ostree initramfs-etc --reboot --track=/etc/ostree/prepare-root.conf
----

. Install https://lix.systems[Lix].
On the Steam Deck, the Determinate Nix installer used here has a dedicated profile that just works.
Of course, I might have just jinxed it now.
Be sure to enable flake support when prompted.
+
[,sh]
----
curl -sSf -L https://install.lix.systems/lix | sh -s -- install
----

. Create the `ccache` directory for Nix.
I configure Nix to use `ccache` to cache compiler outputs to speed up rebuilds.
+
[,sh]
----
sudo mkdir --parents /nix/var/cache/ccache /var/tmp/nix-daemon
----

. Configure your user as an allowed and trusted user for Nix.
Replace `<username>` with the intended user's username.
On the Steam Deck, this user is the `deck` user.
Elsewhere, this is the `jordan` user.
+
./etc/nix/nix.conf
[,ini]
----
allowed-users = <username>
trusted-users = <username>
extra-sandbox-paths = /nix/var/cache/ccache
----

. Restart the Nix daemon.
+
[,sh]
----
sudo systemctl restart nix-daemon.service
----

. Finally, close the current shell and open a new one to make Nix available.
+
[,sh]
----
exit
----

. On Fedora Atomic systems, it's also necessary to ensure `/nix` is mounted early during the boot process so that systemd units in the Nix store can be started properly.

.. Modify `/etc/fstab` to bind-mount `/var/home/nix` to `/nix` with the `x-initrd.mount` option and add the `x-initrd.mount` option to the dependent filesystems, i.e. `/var` and `/var/home`.
The `/etc/fstab` file will look something like this with these changes.
+
./etc/fstab
[,fstab]
----
UUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx /var                    btrfs   subvol=var,compress=zstd:1,x-systemd.device-timeout=0,x-initrd.mount 0 0
UUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx /var/home                   btrfs   subvol=home,compress=zstd:1,x-systemd.device-timeout=0,x-initrd.mount 0 0
/var/home/nix /nix none bind,x-initrd.mount
----

.. Verify the changes to `/etc/fstab` are valid.
+
[,sh]
----
sudo findmnt --verify --verbose
----

. Configure the age key for the user to decrypt the secrets in the {Nix-Secrets} repository.

.. Create the age config directory where the key will reside.
+
[,sh]
----
mkdir --parents ~/.config/sops/age
----

.. Either restore a private age key to the file `~/.config/sops/age/keys.txt` or generate a new key by following these steps.
+
[NOTE]
====
If you restore the age key, be sure to restrict permissions on the file.

[,sh]
----
chmod 0600 ~/.config/sops/age/keys.txt
----
====

... Generate a new private age key at `~/.config/sops/age/keys.txt` with this command.
+
[,sh]
----
nix shell nixpkgs#age --command age-keygen --output ~/.config/sops/age/keys.txt
----

... Back this private key up in a secure password vault.
The following command will print the private key to the console so that it can be copied and saved.
+
[,sh]
----
cat ~/.config/sops/age/keys.txt
----

... A new key must be configured in the {Nix-Secrets} repository.
Since existing users should have had their age key restored, this isn't necessary for existing users.
Refer to the {Nix-Secrets} README for the most up-to-date instructions necessary to add a new user.
It's necessary to have SSH write access to the {Nix-Secrets} repository and that the Forgejo instance is available over Tailscale.
See the previous instructions which document how to configure these prerequisites.

. Clone the Home Manager Config repository.
+
On development systems, clone using SSH::
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/home-manager-config.git
----

On all other systems, such as the Steam Deck, clone using HTTPS::
+
[,sh]
----
git -C ~/Projects clone https://github.com/jwillikers/home-manager-config.git
----

. Change into the repository's directory.
+
[,sh]
----
cd ~/Projects/home-manager-config
----

. Create a symlink to this repository at `~/.config/home-manager` for convenience.
+
[,sh]
----
rm --force --recursive ~/.config/home-manager
ln --force --relative --symbolic . ~/.config/home-manager
----

. Build and activate the Home Manager configuration for this user and host.
+
--
Steam Deck::
+
[,sh]
----
nix develop --command home-manager --flake .#$(id --user --name)@steamdeck switch -b backup
----

Elsewhere::
+
[,sh]
----
nix develop --command home-manager --flake .#$(id --user --name)@$(hostname --short) switch -b backup
----

[TIP]
====
If for any reason the build fails or your computer locks up, there's a good chance that it's related to Nix attempting to build too many jobs simultaneously or not having adequate RAM space to hold the build directory for a package.
These issues can be fixed with configuration options for the Nix daemon in `/etc/nix/nix.conf`.
Use the `max-jobs` option to limit the number of simultaneous jobs.
To build only a single job at a time, this would look like `max-jobs = 1` in the config file.

To prevent running out space in RAM, set the `build-dir` option to a path that is located on disk.
The default `tmp` directory is usually stored in a special filesystem backed by RAM.
To set this to `/var/tmp/nix-daemon`, the line in the config will look like `build-dir = /var/tmp/nix-daemon`.
Be sure to create this directory.

[,sh]
----
sudo mkdir --parents /var/tmp/nix-daemon
----

To apply changes in `/etc/nix/nix.conf`, restart the Nix daemon.

[,sh]
----
sudo systemctl restart nix-daemon.service
----
====

[TIP]
====
If the DeACSM fails during installation, it's necessary to manually delete the plugin and then redeploy the config and re-import your key in Calibre.
The following command will delete the plugin.

[,sh]
----
rm --force --recursive ~/.config/calibre/plugins/ACSM\ Input/ ~/.config/calibre/plugins/ACSM\ Input.zip ~/.config/calibre/plugins/deacsm.json
----
====
--

. Keep an eye on the console output for a message to install the `non-nixos-gpu.service`.
If it appears, run the command shown to install the service.
This is documented in detail https://github.com/nix-community/home-manager/blob/master/docs/manual/usage/gpu-non-nixos.md[here]
When using the NVidia drivers, whenever the system's drivers change it's necessary to update the home-manager configuration so that the Nix driver's version matches the system driver's version exactly.
This requires modifying the version in the configuration file and its associated hash, then rebuilding and running the command from the output to update the systemd unit.
The configuration is located in the file at `_mixins/hardware/<host>/gpu/default.nix`, where `<host>` is the hostname of the machine.
+
[IMPORTANT]
====
On SELinux-enabled systems, it's necessary to relabel the service file in the Nix store so that systemd can load it.
Use the following command to create a permanent SELinux rule for service files matching the pattern of the `non-nixos-gpu.service` in the Nix store.
This rule ensures that the service file is labeled with the `systemd_unit_file_t` type.
This command only needs to be run once.

[,sh]
----
sudo semanage fcontext --add --type systemd_unit_file_t "/nix/store/(.*)-non-nixos-gpu/resources/non-nixos-gpu.service"
----

With that rule in place, the label must be applied to the service file.
Relabel the file with the following command.
This command must be run after every update of the service, I think.
// todo Double check if this is necessary after every update.

[,sh]
----
sudo restorecon -v /nix/store/*-non-nixos-gpu/resources/non-nixos-gpu.service
----

After relabeling, be sure to enable and restart the unit if the update command failed.

[,sh]
----
sudo systemctl enable non-nixos-gpu.service
sudo systemctl restart non-nixos-gpu.service
----
====

. Log out and back in for certain environment variable changes to take effect.

=== Gaming

. Open the Heroic Games Launcher Flatpak and add `~/.nix-profile/bin/heroic-ludusavi-wrapper.sh` as the wrapper command in game config settings.
This must be done per game for any already installed games after changing the global setting.

== Todo

.General Todo
- [ ] Finish the OpenTabletDriver plugin support.
- [ ] Finish optimizing installation of Calibre plugins in the media-juggler home-manager module.
The optimizations are to avoid installing the Calibre plugins on every activation.
The version of the plugin will be compared to what is installed, and only install it then.
- [ ] Use sops-nix to store secrets for the drm Calibre plugin configuration.
- [ ] Manage VSCode profile settings with Nix.
- [ ] Use services.nextcloud-client.enable? How to log in via secrets?

.Hyprland Todo
- [ ] Fix scaling of the UI on the primary monitor.
- [ ] Debug issues with scaling waybar on the primary monitor.
It's too small.
- [ ] Switch to monitorv2
- [ ] Fix Hypridle not activating?

.Stretchly Todo
- [ ] Create a script to move break windows to the correct monitors using the hyprland socket.
- [ ] Create a Wireplumber Lua script to inhibit breaks whenever audio is playing, mic is active, or webcam is recording.
- [ ] Reset breaks in Hypridle

== Resources

* https://nix-community.github.io/home-manager/options.xhtml[Home Manager Configuration Options]
* https://github.com/Misterio77/nix-starter-configs[Misterio77 Nix Starter Config]
* https://github.com/wimpysworld/nix-config[Wimpy's NixOS, nix-darwin & Home Manager Configurations]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[] file.

== License

This repository is licensed under the link:LICENSE[MIT license].

== Copyright

© 2024-2025 Jordan Williams

== Authors

mailto:{email}[{author}]
