name: Build

"on":
  pull_request:
    branches: ["main"]
    paths:
      - "**.nix"
      - .github/workflows/build.yaml
      - flake.lock
  push:
    branches: ["main"]
    paths:
      - "**.nix"
      - .github/workflows/build.yaml
      - flake.lock
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Build x1-yoga
        run: nix develop --command home-manager --flake .#jordan@x1-yoga build
      - name: Build precision5350
        run: nix develop --command home-manager --flake .#jordan@precision5350 build
