name: Build

"on":
  pull_request:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/build.yaml
      - flake.lock
  push:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/build.yaml
      - flake.lock
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build
        run: nix develop --command home-manager --flake .#jordan build
