name: Check Nix Flake
"on":
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/flake-checker.yaml
      - flake.lock
      - '**.nix'

jobs:
  flake-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/flake-checker-action@v12
